services:
  postgres:
    image: 'postgres:latest'
    container_name: ms-email-db
    environment:
      - 'POSTGRES_PASSWORD=1234'
    ports:
      - '5433:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: